# coding: utf-8

"""
    JDX reference application API

    This is a collection of schemas and endpoints for the various JDX, Concentric Sky facing REST endpoints, the schemas define an API contract of sorts between the request and response expectations of the JDX reference application. This API is to be mutually developed by Concentric Sky and BrightHive.  # noqa: E501

    The version of the OpenAPI document: 0.0.17
    Contact: engineering@brighthive.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PreviewObjectAutofill(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'industry_code': 'str',
        'occupation_code': 'str'
    }

    attribute_map = {
        'industry_code': 'industryCode',
        'occupation_code': 'occupationCode'
    }

    def __init__(self, industry_code=None, occupation_code=None):  # noqa: E501
        """PreviewObjectAutofill - a model defined in OpenAPI"""  # noqa: E501

        self._industry_code = None
        self._occupation_code = None
        self.discriminator = None

        if industry_code is not None:
            self.industry_code = industry_code
        if occupation_code is not None:
            self.occupation_code = occupation_code

    @property
    def industry_code(self):
        """Gets the industry_code of this PreviewObjectAutofill.  # noqa: E501


        :return: The industry_code of this PreviewObjectAutofill.  # noqa: E501
        :rtype: str
        """
        return self._industry_code

    @industry_code.setter
    def industry_code(self, industry_code):
        """Sets the industry_code of this PreviewObjectAutofill.


        :param industry_code: The industry_code of this PreviewObjectAutofill.  # noqa: E501
        :type: str
        """

        self._industry_code = industry_code

    @property
    def occupation_code(self):
        """Gets the occupation_code of this PreviewObjectAutofill.  # noqa: E501


        :return: The occupation_code of this PreviewObjectAutofill.  # noqa: E501
        :rtype: str
        """
        return self._occupation_code

    @occupation_code.setter
    def occupation_code(self, occupation_code):
        """Sets the occupation_code of this PreviewObjectAutofill.


        :param occupation_code: The occupation_code of this PreviewObjectAutofill.  # noqa: E501
        :type: str
        """

        self._occupation_code = occupation_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreviewObjectAutofill):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
